### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by enseitankado** [yashksagar/ViewsCounter#1]
Project not functional.

**Comment by yashk-coursera** [comment]
hey @enseitankado, thanks for stopping by and sorry about that! This was a college side project I did a while ago, and I'm not surprised that YouTube has updated their APIs since then :)

I will update the readme to make this clearer. In retrospect, I should have at least grabbed a screen recording of the app. 

Ah well  ¯\_(ツ)_/¯
